services:
  oryx:
    image: ossrs/oryx:5
    ports:
      - "2022:2022"
      - "2443:2443"
      - "1935:1935"
      - "8000:8000/udp"
      - "10080:10080/udp"
    environment:
      # https://ossrs.net/lts/en-us/docs/v4/doc/webrtc#config-candidate
      - CANDIDATE=192.168.100.2
    volumes:
      - $HOME/data:/data

  frontend:
    image: caddy:2
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./public:/app
